[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "nh3"
version = "0.2.17"
description = "Python bindings to the ammonia HTML sanitization library."
license = "MIT"
readme = "README.md"

[tool.maturin]
features = ["pyo3/extension-module"]
